name: issue-actions

on:
  issues:
    branches: opened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-files
          path: ${{ github.workspace }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
